//! Generates the built-in catalog's file list.
//!
//! The built-in catalog ships one TOML file per provider under
//! `src/catalog/builtin/`. This script enumerates the directory and writes
//! a `BUILTIN_FILES` constant into `OUT_DIR`, so adding a provider means
//! adding a file and nothing else. The loader includes the generated
//! constant under the `builtin-catalog` feature.

#![allow(
    clippy::print_stdout,
    reason = "cargo build-script directives are stdout lines"
)]

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

fn main() {
    let dir = PathBuf::from("src/catalog/builtin");
    // A directory entry only tracks additions and removals; each file must
    // be watched itself for content edits to rebuild the constant's data.
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut names: Vec<String> = fs::read_dir(&dir)
        .expect("the built-in catalog directory should exist")
        .map(|entry| {
            entry
                .expect("the built-in catalog directory should be readable")
                .file_name()
                .into_string()
                .expect("a built-in catalog file name should be UTF-8")
        })
        .filter(|name| {
            Path::new(name)
                .extension()
                .is_some_and(|extension| extension.eq_ignore_ascii_case("toml"))
        })
        .collect();
    names.sort();
    assert!(
        !names.is_empty(),
        "the built-in catalog directory holds no TOML files"
    );

    let mut generated = String::from(
        "/// The built-in reference catalog, one file per provider.\n\
         ///\n\
         /// Generated by `build.rs` from `src/catalog/builtin/*.toml`, in\n\
         /// file-name order. Each file is a standalone catalog layer.\n\
         #[cfg(feature = \"builtin-catalog\")]\n\
         const BUILTIN_FILES: &[(&str, &str)] = &[\n",
    );
    for name in &names {
        println!("cargo:rerun-if-changed={}", dir.join(name).display());
        writeln!(
            generated,
            "    (\"built-in/{name}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/src/catalog/builtin/{name}\"))),"
        )
        .expect("writing to a string cannot fail");
    }
    generated.push_str("];\n");

    let out = PathBuf::from(env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    fs::write(out.join("builtin_files.rs"), generated)
        .expect("the generated file list should be writable");
}
