use std::collections::BTreeMap;

use serde::Deserialize;
use toml::Value;
use toml::map::Map;

use super::overlay::merge;
use super::{Catalog, CatalogDocument, CatalogError, CatalogProvider, LayerOrigins, ProviderId};

// `BUILTIN_FILES`: the built-in reference catalog, one file per provider.
// Generated by `build.rs` from `src/catalog/builtin/*.toml`, so growing the
// catalog by one provider means adding one file and nothing else. A parse or
// validation failure names the exact file.
include!(concat!(env!("OUT_DIR"), "/builtin_files.rs"));

/// The layer name reported when a failure belongs to no single layer.
const MERGED_LAYER: &str = "<merged catalog>";

struct Layer {
    name:   String,
    source: LayerSource,
}

enum LayerSource {
    Builtin,
    Toml(Value),
}

/// The merged document before provider entries are given their schema.
///
/// Providers stay as raw TOML so a schema failure can name the layer that
/// last wrote the offending provider.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawDocument {
    schema_version: u32,
    providers:      BTreeMap<ProviderId, Value>,
}

/// Builds an immutable catalog from ordered layers.
///
/// Layers merge in call order and later layers win. Each layer carries a name
/// that appears in parse and validation errors. No layer is added implicitly:
/// a catalog built only from application TOML contains no built-in entry.
#[derive(Default)]
#[must_use]
pub struct CatalogBuilder {
    layers:   Vec<Layer>,
    overlays: usize,
}

impl CatalogBuilder {
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds the built-in reference catalog as the next layers.
    ///
    /// The catalog ships one file per provider; each becomes its own layer,
    /// named `built-in/<provider>.toml`.
    pub fn with_builtin(mut self) -> Self {
        self.layers.push(Layer {
            name:   String::new(),
            source: LayerSource::Builtin,
        });
        self
    }

    /// Adds a named TOML layer.
    ///
    /// `name` identifies the layer in parse and validation errors. A file path
    /// such as `providers/openai.toml` reads well in a message.
    ///
    /// # Errors
    ///
    /// Returns [`CatalogError::Parse`] when `source` is not valid TOML.
    pub fn toml_layer(
        mut self,
        name: impl Into<String>,
        source: &str,
    ) -> Result<Self, CatalogError> {
        let name = name.into();
        let value = parse_layer(&name, source)?;
        self.layers.push(Layer {
            name,
            source: LayerSource::Toml(value),
        });
        Ok(self)
    }

    /// Adds an unnamed TOML layer.
    ///
    /// The layer is named `overlay 1`, `overlay 2`, and so on by position. Use
    /// [`CatalogBuilder::toml_layer`] to choose a more useful name.
    ///
    /// # Errors
    ///
    /// Returns [`CatalogError::Parse`] when `source` is not valid TOML.
    pub fn overlay_toml(mut self, source: &str) -> Result<Self, CatalogError> {
        self.overlays += 1;
        let name = format!("overlay {}", self.overlays);
        self.toml_layer(name, source)
    }

    /// Merges every layer and validates the result.
    ///
    /// # Errors
    ///
    /// Returns [`CatalogError::Parse`] when a merged provider does not match
    /// the catalog schema, [`CatalogError::Layer`] when a provider fails
    /// validation and its layer is known, and the underlying
    /// [`CatalogError`] otherwise.
    pub fn build(self) -> Result<Catalog, CatalogError> {
        let mut merged = Value::Table(Map::new());
        let mut origins = LayerOrigins::new();
        for layer in self.layers {
            match layer.source {
                LayerSource::Builtin => {
                    for (name, value) in builtin_layers()? {
                        record_origins(&mut origins, name, &value);
                        merge(&mut merged, value);
                    }
                }
                LayerSource::Toml(value) => {
                    record_origins(&mut origins, &layer.name, &value);
                    merge(&mut merged, value);
                }
            }
        }

        let raw: RawDocument = merged.try_into().map_err(|source| CatalogError::Parse {
            layer: MERGED_LAYER.to_owned(),
            source,
        })?;

        let mut providers = BTreeMap::new();
        for (provider_id, value) in raw.providers {
            let layer = origins
                .get(&provider_id)
                .cloned()
                .unwrap_or_else(|| MERGED_LAYER.to_owned());
            let provider: CatalogProvider = value
                .try_into()
                .map_err(|source| CatalogError::Parse { layer, source })?;
            providers.insert(provider_id, provider);
        }

        Catalog::from_document(
            CatalogDocument {
                schema_version: raw.schema_version,
                providers,
            },
            &origins,
        )
    }
}

fn parse_layer(layer: &str, source: &str) -> Result<Value, CatalogError> {
    toml::from_str(source).map_err(|error| CatalogError::Parse {
        layer:  layer.to_owned(),
        source: error,
    })
}

/// Records `layer` as the most recent writer of every provider it declares.
fn record_origins(origins: &mut LayerOrigins, layer: &str, value: &Value) {
    let Some(Value::Table(providers)) = value.get("providers") else {
        return;
    };
    for name in providers.keys() {
        origins.insert(ProviderId::new(name.clone()), layer.to_owned());
    }
}

#[cfg(feature = "builtin-catalog")]
fn builtin_layers() -> Result<Vec<(&'static str, Value)>, CatalogError> {
    BUILTIN_FILES
        .iter()
        .map(|(name, source)| Ok((*name, parse_layer(name, source)?)))
        .collect()
}

#[cfg(not(feature = "builtin-catalog"))]
fn builtin_layers() -> Result<Vec<(&'static str, Value)>, CatalogError> {
    Err(CatalogError::BuiltinCatalogDisabled)
}

#[cfg(test)]
mod tests {
    use std::error::Error as StdError;

    use serde::Deserialize;

    use super::{Catalog, CatalogError};
    #[cfg(feature = "builtin-catalog")]
    use crate::catalog::{AuthScheme, Metadata};
    #[cfg(feature = "builtin-catalog")]
    use crate::types::Speed;

    /// The agent profiles a catalog row may name.
    ///
    /// An agent runtime picks one prompting and tool convention per route from
    /// this value, so an unknown string is a build failure there rather than a
    /// fallback. The set matches fabro's `AgentProfileKind`.
    #[cfg(feature = "builtin-catalog")]
    const AGENT_PROFILES: [&str; 6] =
        ["anthropic", "claude-5", "openai", "gemini", "kimi", "gpt56"];

    const BASE: &str = r#"
        schema_version = 1

        [providers.first]
        display_name = "First"
        adapter = "custom"
        codec = "custom"
        base_url = "https://example.com"
        auth = { type = "none" }

        [providers.first.models.model]
        display_name = "Model"
        api_model = "model"
    "#;

    #[derive(Debug, Deserialize, Eq, PartialEq)]
    struct AppMetadata {
        latency: String,
        nested:  Nested,
    }

    #[derive(Debug, Deserialize, Eq, PartialEq)]
    struct Nested {
        enabled: bool,
        count:   u64,
    }

    /// The `pebble` metadata namespace, read the way its application reads it.
    #[cfg(feature = "builtin-catalog")]
    #[derive(Debug, Deserialize)]
    struct PebbleMetadata {
        profile: Option<String>,
    }

    /// The agent profile a row names, if it names one.
    #[cfg(feature = "builtin-catalog")]
    fn agent_profile(metadata: &Metadata) -> Result<Option<String>, Box<dyn StdError>> {
        Ok(metadata
            .namespace::<PebbleMetadata>("pebble")?
            .and_then(|pebble| pebble.profile))
    }

    #[test]
    fn external_layers_add_no_built_in_entry() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .build()?;

        assert_eq!(catalog.providers().len(), 1);
        assert!(catalog.provider("openai").is_err());
        assert!(catalog.provider("anthropic").is_err());
        assert!(catalog.models_matching("gpt-5.6-luna").is_empty());
        Ok(())
    }

    #[test]
    fn merges_named_layers_in_call_order() -> Result<(), Box<dyn StdError>> {
        let priority = r"
            [providers.first]
            priority = 10
        ";
        let second = r#"
            [providers.second]
            display_name = "Second"
            adapter = "custom"
            codec = "custom"
            base_url = "https://second.example.com"
            auth = { type = "none" }
        "#;
        let later = r"
            [providers.first]
            priority = 20
        ";

        let catalog = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("providers/first.toml", priority)?
            .toml_layer("providers/second.toml", second)?
            .toml_layer("overrides.toml", later)?
            .build()?;

        let ids = catalog
            .providers()
            .map(|provider| provider.id().as_str().to_owned())
            .collect::<Vec<_>>();

        assert_eq!(ids, vec!["first".to_owned(), "second".to_owned()]);
        assert_eq!(catalog.provider("first")?.priority(), 20);
        Ok(())
    }

    #[test]
    fn reports_the_layer_name_for_invalid_toml() -> Result<(), Box<dyn StdError>> {
        let result = Catalog::builder().toml_layer("providers/broken.toml", "not = = toml");

        let Err(CatalogError::Parse { layer, .. }) = result.map(|_| ()) else {
            return Err("expected a parse failure".into());
        };
        assert_eq!(layer, "providers/broken.toml");
        Ok(())
    }

    #[test]
    fn reports_the_layer_name_for_a_validation_failure() -> Result<(), Box<dyn StdError>> {
        let broken = r#"
            [providers.first]
            default_model = "missing"
        "#;

        let result = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("providers/first.toml", broken)?
            .build();

        let Err(CatalogError::Layer { layer, source }) = result else {
            return Err("expected a layer failure".into());
        };
        assert_eq!(layer, "providers/first.toml");
        assert!(matches!(
            *source,
            CatalogError::UnknownDefaultModel { model, .. } if model == "missing"
        ));
        Ok(())
    }

    #[test]
    fn reports_the_layer_name_for_an_unknown_provider_field() -> Result<(), Box<dyn StdError>> {
        let unknown = r#"
            [providers.first]
            base_urls = "https://example.com"
        "#;

        let result = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("providers/first.toml", unknown)?
            .build();

        let Err(CatalogError::Parse { layer, source }) = result else {
            return Err("expected a schema failure".into());
        };
        assert_eq!(layer, "providers/first.toml");
        assert!(source.to_string().contains("base_urls"));
        Ok(())
    }

    #[test]
    fn rejects_an_unknown_model_field() -> Result<(), Box<dyn StdError>> {
        let unknown = r"
            [providers.first.models.model]
            context_window = 4096
        ";

        let result = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("providers/first.toml", unknown)?
            .build();

        let Err(CatalogError::Parse { layer, source }) = result else {
            return Err("expected a schema failure".into());
        };
        assert_eq!(layer, "providers/first.toml");
        assert!(source.to_string().contains("context_window"));
        Ok(())
    }

    #[test]
    fn round_trips_namespaced_metadata() -> Result<(), Box<dyn StdError>> {
        let first = r#"
            [providers.first.models.model.metadata.app]
            latency = "fast"
            nested = { enabled = true }
        "#;
        let second = r"
            [providers.first.models.model.metadata.app.nested]
            count = 2
        ";

        let catalog = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("app/first.toml", first)?
            .toml_layer("app/second.toml", second)?
            .build()?;

        let metadata = catalog
            .model("first", "model")?
            .metadata()
            .namespace::<AppMetadata>("app")?
            .ok_or("app metadata should be present")?;

        assert_eq!(metadata, AppMetadata {
            latency: "fast".to_owned(),
            nested:  Nested {
                enabled: true,
                count:   2,
            },
        });
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn overlays_catalog_and_recursively_merges_metadata() -> Result<(), Box<dyn StdError>> {
        let first = r#"
            [providers.openai.models."gpt-5.6-luna".metadata.app]
            latency = "fast"
            nested = { enabled = true }
        "#;
        let second = r#"
            [providers.openai.models."gpt-5.6-luna".metadata.app.nested]
            count = 2
        "#;
        let catalog = Catalog::builder()
            .with_builtin()
            .overlay_toml(first)?
            .overlay_toml(second)?
            .build()?;

        let metadata = catalog
            .model("openai", "luna")?
            .metadata()
            .namespace::<AppMetadata>("app")?
            .ok_or("app metadata should be present")?;
        assert_eq!(metadata, AppMetadata {
            latency: "fast".to_owned(),
            nested:  Nested {
                enabled: true,
                count:   2,
            },
        });
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn names_unnamed_overlays_by_position() -> Result<(), Box<dyn StdError>> {
        let broken = r#"
            [providers.openai]
            default_model = "missing"
        "#;

        let result = Catalog::builder()
            .with_builtin()
            .overlay_toml("")?
            .overlay_toml(broken)?
            .build();

        let Err(CatalogError::Layer { layer, .. }) = result else {
            return Err("expected a layer failure".into());
        };
        assert_eq!(layer, "overlay 2");
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn the_builtin_venice_provider_resolves_verified_routes() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        let venice = catalog.provider("venice")?;
        assert_eq!(venice.default_model(), Some("deepseek-v4-flash"));
        assert!(
            venice.default_options().contains_key("venice_parameters"),
            "the venice row should turn off the injected system prompt"
        );

        // The fabro aliases survive and resolve to the verified wire ids.
        assert_eq!(
            catalog.model("venice", "kimi-fast")?.api_model(),
            "kimi-k3-fast-api"
        );
        assert_eq!(
            catalog.model("venice", "deepseek")?.api_model(),
            "deepseek-v4-flash-0731"
        );
        assert_eq!(
            catalog.model("venice", "claude-opus-4.8")?.api_model(),
            "claude-opus-4-8"
        );

        // Fable 5.1 keeps Venice's Claude flags but takes no forced tool
        // choice, and Venice lists it at Anthropic's own rates.
        let fable_51 = catalog.model("venice", "claude-fable-5.1")?;
        assert_eq!(fable_51.api_model(), "claude-fable-5-1");
        assert!(!fable_51.capabilities().forced_tool_choice);
        assert!(fable_51.capabilities().sampling);
        assert!(fable_51.capabilities().cache_routing);
        assert_eq!(
            fable_51.pricing().map(|pricing| (
                pricing.input_usd_micros_per_million,
                pricing.cached_input_usd_micros_per_million,
            )),
            Some((Some(10_000_000), Some(250_000)))
        );
        assert!(
            catalog
                .model("venice", "claude-fable-5")?
                .capabilities()
                .forced_tool_choice
        );

        // Live-verified capability corrections win over fabro's claims.
        assert!(
            !catalog
                .model("venice", "qwen3.8-max")?
                .capabilities()
                .structured_output
        );
        assert!(
            catalog
                .model("venice", "kimi-k3")?
                .capabilities()
                .reasoning_effort_levels
        );
        assert!(
            !catalog
                .model("venice", "glm-5.3")?
                .capabilities()
                .reasoning_effort_levels
        );

        // A model id shared with another provider stays reachable through
        // the explicit selector; bare-id resolution is priority-ordered and
        // is pinned by the resolver tests.
        assert_eq!(
            catalog.model("venice", "gpt-5.6-luna")?.api_model(),
            "openai-gpt-56-luna"
        );
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn the_builtin_openrouter_provider_resolves_verified_routes() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        let openrouter = catalog.provider("openrouter")?;
        assert_eq!(openrouter.default_model(), Some("claude-sonnet-5"));

        assert_eq!(
            catalog.model("openrouter", "sonnet")?.api_model(),
            "anthropic/claude-sonnet-5"
        );
        // The `fable` alias stays on Fable 5; 5.1 is reached by its own id and
        // is the one Claude row that takes no forced tool choice.
        let fable = catalog.model("openrouter", "fable")?;
        assert_eq!(fable.api_model(), "anthropic/claude-fable-5");
        assert!(fable.capabilities().forced_tool_choice);
        let fable_51 = catalog.model("openrouter", "claude-fable-5.1")?;
        assert_eq!(fable_51.api_model(), "anthropic/claude-fable-5.1");
        assert!(!fable_51.capabilities().forced_tool_choice);
        assert!(fable_51.capabilities().cache_breakpoints);
        assert_eq!(
            fable_51
                .pricing()
                .and_then(|pricing| pricing.cached_input_usd_micros_per_million),
            Some(250_000)
        );
        assert_eq!(
            catalog.model("openrouter", "deepseek")?.api_model(),
            "deepseek/deepseek-v4-flash-0731"
        );
        assert_eq!(
            catalog.model("openrouter", "grok-4.6")?.api_model(),
            "x-ai/grok-4.6"
        );

        let flash = catalog.model("openrouter", "gemini-3.5-flash")?;
        assert!(flash.capabilities().structured_output);
        assert!(flash.capabilities().reasoning_effort_levels);
        assert!(!flash.capabilities().audio);
        assert!(
            !catalog
                .model("openrouter", "qwen3.6-flash")?
                .capabilities()
                .structured_output
        );

        let sol = catalog.model("openrouter", "gpt-5.6-sol")?;
        let pricing = sol.pricing().ok_or("gpt-5.6-sol should be priced")?;
        assert_eq!(pricing.input_usd_micros_per_million, Some(2_000_000));
        assert_eq!(
            pricing
                .long_context
                .as_ref()
                .and_then(|rates| rates.output_usd_micros_per_million),
            Some(15_000_000)
        );
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn the_builtin_fireworks_provider_resolves_verified_routes() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        let fireworks = catalog.provider("fireworks")?;
        assert_eq!(fireworks.default_model(), Some("kimi-k2.7-code"));
        assert!(fireworks.allows_passthrough());
        assert_eq!(
            catalog.model("fireworks", "deepseek")?.api_model(),
            "accounts/fireworks/models/deepseek-v4-flash-0731"
        );
        assert_eq!(
            catalog.model("fireworks", "glm-5.3")?.api_model(),
            "accounts/fireworks/models/glm-5p3"
        );

        let kimi = catalog.model("fireworks", "kimi-k2.6")?;
        assert!(kimi.capabilities().images);
        assert!(kimi.capabilities().reasoning);

        let pro = catalog.model("fireworks", "deepseek-v4-pro")?;
        let pricing = pro.pricing().ok_or("DeepSeek V4 Pro should be priced")?;
        assert_eq!(pricing.input_usd_micros_per_million, Some(1_320_000));
        assert_eq!(pricing.cached_input_usd_micros_per_million, Some(44_000));

        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn the_builtin_anthropic_provider_resolves_verified_routes() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        let anthropic = catalog.provider("claude")?;
        assert_eq!(anthropic.default_model(), Some("claude-sonnet-5"));
        assert!(anthropic.allows_passthrough());
        assert_eq!(
            catalog.model("anthropic", "sonnet")?.api_model(),
            "claude-sonnet-5"
        );

        let fable = catalog.model("anthropic", "fable")?;
        assert_eq!(
            fable
                .limits()
                .map(|limits| (limits.context_tokens, limits.max_output_tokens)),
            Some((1_000_000, 128_000))
        );
        assert!(fable.capabilities().reasoning_effort_levels);
        assert!(!fable.capabilities().sampling);
        assert!(fable.capabilities().forced_tool_choice);

        // Fable 5.1 shares Fable 5's limits and rates except for cache reads,
        // and is the one row that takes no forced tool choice.
        let fable_51 = catalog.model("anthropic", "claude-fable-5.1")?;
        assert_eq!(fable_51.api_model(), "claude-fable-5-1");
        assert_eq!(fable_51.limits(), fable.limits());
        assert!(fable_51.capabilities().reasoning_effort_levels);
        assert!(!fable_51.capabilities().sampling);
        assert!(!fable_51.capabilities().forced_tool_choice);

        // System turns: the Claude 5 rows and Opus 4.8 take them, the older
        // rows reject them, so the codec hoists there.
        assert!(fable_51.capabilities().system_turns);
        assert!(fable.capabilities().system_turns);
        assert!(
            catalog
                .model("anthropic", "claude-sonnet-5")?
                .capabilities()
                .system_turns
        );
        assert!(
            catalog
                .model("anthropic", "claude-opus-4.8")?
                .capabilities()
                .system_turns
        );
        assert!(
            !catalog
                .model("anthropic", "claude-opus-4.7")?
                .capabilities()
                .system_turns
        );
        assert!(
            !catalog
                .model("anthropic", "claude-haiku-4.5")?
                .capabilities()
                .system_turns
        );
        let fable_51_pricing = fable_51.pricing().ok_or("Fable 5.1 must be priced")?;
        assert_eq!(
            fable_51_pricing.cached_input_usd_micros_per_million,
            Some(250_000)
        );
        assert_eq!(
            fable_51_pricing.input_usd_micros_per_million,
            fable.pricing().and_then(|p| p.input_usd_micros_per_million)
        );

        let sonnet_45 = catalog.model("anthropic", "claude-sonnet-4.5")?;
        assert_eq!(
            sonnet_45
                .limits()
                .map(|limits| (limits.context_tokens, limits.max_output_tokens)),
            Some((200_000, 64_000))
        );
        assert!(!sonnet_45.capabilities().reasoning_effort_levels);
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn the_builtin_gemini_provider_resolves_verified_routes() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        let gemini = catalog.provider("google")?;
        assert_eq!(gemini.default_model(), Some("gemini-3.5-flash"));
        assert!(gemini.allows_passthrough());
        assert_eq!(
            catalog.model("gemini", "gemini-pro")?.api_model(),
            "gemini-3.1-pro-preview"
        );

        let flash = catalog.model("gemini", "gemini-3.5-flash")?;
        assert_eq!(
            flash
                .limits()
                .map(|limits| (limits.context_tokens, limits.max_output_tokens)),
            Some((1_048_576, 65_536))
        );
        assert!(flash.capabilities().reasoning);
        assert!(flash.capabilities().reasoning_effort_levels);
        assert!(flash.capabilities().sampling);
        assert_eq!(
            flash
                .pricing()
                .and_then(|pricing| pricing.cached_input_usd_micros_per_million),
            Some(150_000)
        );
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn the_builtin_modal_provider_is_portable_passthrough() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        let modal = catalog.provider("modal")?;
        assert_eq!(
            modal.base_url(),
            "https://inference.us-west.modal.direct/v1"
        );
        assert!(matches!(modal.auth(), AuthScheme::Headers));
        assert!(modal.allows_passthrough());
        assert!(modal.default_model().is_none());
        assert_eq!(modal.models().len(), 0);
        assert_eq!(
            modal
                .metadata()
                .get("fabro")
                .and_then(|value| value["agent_profile"].as_str()),
            Some("kimi")
        );
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn the_builtin_moonshot_provider_resolves_verified_routes() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        let moonshot = catalog.provider("moonshot")?;
        assert_eq!(moonshot.default_model(), Some("kimi-k3"));
        assert!(moonshot.allows_passthrough());
        assert_eq!(catalog.model("moonshot", "kimi")?.api_model(), "kimi-k3");

        let k3 = catalog.model("moonshot", "kimi-k3")?;
        assert_eq!(
            k3.limits()
                .map(|limits| (limits.context_tokens, limits.max_output_tokens)),
            Some((1_048_576, 1_048_576))
        );
        assert!(k3.capabilities().reasoning_effort_levels);
        assert!(!k3.capabilities().sampling);

        let fabro = k3
            .metadata()
            .get("fabro")
            .ok_or("Kimi K3 should preserve fabro metadata")?;
        assert_eq!(fabro["family"], "kimi-k3");
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn the_builtin_openai_provider_resolves_verified_routes() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        let openai = catalog.provider("openai")?;
        assert_eq!(openai.default_model(), Some("gpt-5.6-sol"));
        assert!(openai.allows_passthrough());
        assert_eq!(catalog.model("openai", "luna")?.api_model(), "gpt-5.6-luna");
        // fabro routes its legacy short names at the current codex driver.
        assert_eq!(catalog.model("openai", "codex")?.api_model(), "gpt-5.4");
        assert_eq!(
            catalog.model("openai", "gpt-5.6")?.api_model(),
            "gpt-5.6-sol"
        );

        // Sampling controls are model-specific on the live API (2026-08-30):
        // the 5.4 rows take temperature, the 5.5 and 5.6 rows reject it.
        assert!(catalog.model("openai", "gpt-5.4")?.capabilities().sampling);
        assert!(
            catalog
                .model("openai", "gpt-5.4-mini")?
                .capabilities()
                .sampling
        );
        assert!(!catalog.model("openai", "gpt-5.5")?.capabilities().sampling);
        assert!(
            !catalog
                .model("openai", "gpt-5.6-sol")?
                .capabilities()
                .sampling
        );

        // The pro rows cache nothing and price no speed tier, so the local
        // speed gate refuses fast and economical for them.
        let pro = catalog.model("openai", "gpt-5.5-pro")?;
        assert!(!pro.capabilities().caching);
        let pricing = pro.pricing().ok_or("gpt-5.5-pro should be priced")?;
        assert!(pricing.speed.is_none());

        let mini = catalog.model("openai", "gpt-5.4-mini")?;
        assert_eq!(
            mini.limits()
                .map(|limits| (limits.context_tokens, limits.max_output_tokens)),
            Some((400_000, 128_000))
        );
        let fabro = mini
            .metadata()
            .get("fabro")
            .ok_or("gpt-5.4-mini should preserve fabro metadata")?;
        assert_eq!(fabro["probe"], true);
        assert_eq!(fabro["small_default"], true);
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn the_builtin_catalog_carries_the_published_rates_and_limits() -> Result<(), Box<dyn StdError>>
    {
        let catalog = Catalog::builder().with_builtin().build()?;

        // OpenAI's published rates and limits, verified live on 2026-08-30.
        // Luna's window is 1,050,000 tokens; 272,000 is the long-context
        // billing threshold, and the 5.6 family bills cache writes at 1.25x.
        let luna = catalog.model("openai", "gpt-5.6-luna")?;
        let pricing = luna.pricing().ok_or("gpt-5.6-luna should be priced")?;
        assert_eq!(pricing.input_usd_micros_per_million, Some(200_000));
        assert_eq!(pricing.output_usd_micros_per_million, Some(1_200_000));
        assert_eq!(pricing.cached_input_usd_micros_per_million, Some(20_000));
        assert_eq!(pricing.cache_write_usd_micros_per_million, Some(250_000));
        assert_eq!(
            luna.limits().map(|limits| limits.context_tokens),
            Some(1_050_000)
        );
        let long = pricing.for_input_tokens(300_000);
        assert_eq!(long.input_usd_micros_per_million, Some(400_000));
        assert_eq!(long.output_usd_micros_per_million, Some(1_800_000));
        let fast = pricing.for_speed(Some(Speed::Fast));
        assert_eq!(fast.input_usd_micros_per_million, Some(400_000));
        let flex = pricing.for_speed(Some(Speed::Economical));
        assert_eq!(flex.input_usd_micros_per_million, Some(100_000));

        let sonnet = catalog.model("anthropic", "claude-sonnet-4-6")?;
        assert_eq!(
            sonnet.limits().map(|limits| limits.context_tokens),
            Some(1_000_000)
        );
        assert_eq!(
            sonnet.limits().map(|limits| limits.max_output_tokens),
            Some(128_000)
        );
        let pricing = sonnet
            .pricing()
            .ok_or("claude-sonnet-4-6 should be priced")?;
        // Anthropic bills a cache write at 1.25x input. The entry carries no
        // fast-tier rates, so a fast request keeps the base rates rather than
        // reporting an invented premium.
        assert_eq!(pricing.cache_write_usd_micros_per_million, Some(3_750_000));
        let fast = pricing.for_speed(Some(Speed::Fast));
        assert_eq!(fast.input_usd_micros_per_million, Some(3_000_000));
        assert_eq!(fast.output_usd_micros_per_million, Some(15_000_000));
        assert!(sonnet.capabilities().reasoning_effort_levels);

        // Bedrock on-demand access needs the `us.` inference profile, and the
        // model caches, which the codec gates on.
        let bedrock = catalog.model("bedrock", "anthropic.claude-sonnet-4-6")?;
        assert_eq!(bedrock.api_model(), "us.anthropic.claude-sonnet-4-6");
        assert!(bedrock.capabilities().caching);
        assert!(bedrock.capabilities().reasoning_effort_levels);
        assert_eq!(
            bedrock.limits().map(|limits| limits.max_output_tokens),
            Some(64_000)
        );
        let pricing = bedrock
            .pricing()
            .ok_or("the Bedrock model should be priced")?;
        assert_eq!(pricing.input_usd_micros_per_million, Some(3_000_000));
        assert_eq!(pricing.output_usd_micros_per_million, Some(15_000_000));
        assert_eq!(pricing.cached_input_usd_micros_per_million, Some(300_000));
        assert_eq!(pricing.cache_write_usd_micros_per_million, Some(3_750_000));
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn a_model_agent_profile_overrides_its_provider() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        // The Anthropic provider row carries the profile a passthrough model
        // gets; every catalogued Claude row names the current one instead.
        assert_eq!(
            agent_profile(catalog.provider("anthropic")?.metadata())?.as_deref(),
            Some("anthropic")
        );
        assert_eq!(
            agent_profile(catalog.model("anthropic", "sonnet")?.metadata())?.as_deref(),
            Some("claude-5")
        );

        // A model row that names no profile of its own leaves the provider's
        // value in force.
        assert_eq!(
            agent_profile(catalog.model("openai", "gpt-5.4")?.metadata())?,
            None
        );
        assert_eq!(
            agent_profile(catalog.provider("openai")?.metadata())?.as_deref(),
            Some("openai")
        );
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn every_builtin_row_resolves_a_known_agent_profile() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        for provider in catalog.providers() {
            let id = provider.id();
            let default = agent_profile(provider.metadata())?
                .ok_or_else(|| format!("provider `{id}` names no agent profile"))?;
            assert!(
                AGENT_PROFILES.contains(&default.as_str()),
                "provider `{id}` names the unknown agent profile `{default}`"
            );

            for model in provider.models() {
                let profile = agent_profile(model.metadata())?.unwrap_or_else(|| default.clone());
                assert!(
                    AGENT_PROFILES.contains(&profile.as_str()),
                    "`{id}/{}` resolves the unknown agent profile `{profile}`",
                    model.id()
                );
            }
        }
        Ok(())
    }

    #[test]
    fn rejects_provider_alias_that_collides_with_an_id() -> Result<(), Box<dyn StdError>> {
        let source = r#"
            schema_version = 1
            [providers.first]
            display_name = "First"
            aliases = ["second"]
            adapter = "custom"
            codec = "custom"
            base_url = "https://example.com"
            auth = { type = "none" }

            [providers.second]
            display_name = "Second"
            adapter = "custom"
            codec = "custom"
            base_url = "https://example.com"
            auth = { type = "none" }
        "#;

        let result = Catalog::builder().overlay_toml(source)?.build();

        let Err(CatalogError::Layer { source, .. }) = result else {
            return Err("expected a layer failure".into());
        };
        assert!(matches!(
            *source,
            CatalogError::DuplicateProviderAlias { alias } if alias == "second"
        ));
        Ok(())
    }

    #[test]
    fn rejects_duplicate_model_selector_within_provider() -> Result<(), Box<dyn StdError>> {
        let source = r#"
            schema_version = 1
            [providers.test]
            display_name = "Test"
            adapter = "custom"
            codec = "custom"
            base_url = "https://example.com"
            auth = { type = "none" }

            [providers.test.models.first]
            display_name = "First"
            aliases = ["shared"]
            api_model = "first"

            [providers.test.models.second]
            display_name = "Second"
            aliases = ["shared"]
            api_model = "second"
        "#;

        let result = Catalog::builder().overlay_toml(source)?.build();

        let Err(CatalogError::Layer { layer, source }) = result else {
            return Err("expected a layer failure".into());
        };
        assert_eq!(layer, "overlay 1");
        assert!(matches!(
            *source,
            CatalogError::DuplicateModelSelector { provider, selector }
                if provider.as_str() == "test" && selector == "shared"
        ));
        Ok(())
    }
}
