use std::collections::BTreeMap;

use serde::Deserialize;
use toml::Value;
use toml::map::Map;

use super::overlay::merge;
use super::{Catalog, CatalogError, LayerOrigins, ParsedCatalogDocument, ProviderId};

// `BUILTIN_FILES`: the built-in reference catalog, one file per provider.
// Generated by `build.rs` from `src/catalog/builtin/*.toml`, so growing the
// catalog by one provider means adding one file and nothing else. A parse or
// validation failure names the exact file.
include!(concat!(env!("OUT_DIR"), "/builtin_files.rs"));

/// The layer name reported when a failure belongs to no single layer.
const MERGED_LAYER: &str = "<merged catalog>";

struct Layer {
    name:   String,
    source: LayerSource,
}

enum LayerSource {
    Builtin,
    Toml(Value),
}

/// The merged document before provider entries are given their schema.
///
/// Providers stay as raw TOML so a schema failure can name the layer that
/// last wrote the offending provider.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawDocument {
    schema_version: u32,
    providers:      BTreeMap<ProviderId, Value>,
}

/// Builds an immutable catalog from ordered layers.
///
/// Layers merge in call order and later layers win. Each layer carries a name
/// that appears in parse and validation errors. No layer is added implicitly:
/// a catalog built only from application TOML contains no built-in entry.
#[derive(Default)]
#[must_use]
pub struct CatalogBuilder {
    layers:   Vec<Layer>,
    overlays: usize,
}

impl CatalogBuilder {
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds the built-in reference catalog as the next layers.
    ///
    /// The catalog ships one file per provider; each becomes its own layer,
    /// named `built-in/<provider>.toml`.
    pub fn with_builtin(mut self) -> Self {
        self.layers.push(Layer {
            name:   String::new(),
            source: LayerSource::Builtin,
        });
        self
    }

    /// Adds a named TOML layer.
    ///
    /// `name` identifies the layer in parse and validation errors. A file path
    /// such as `providers/openai.toml` reads well in a message.
    ///
    /// # Errors
    ///
    /// Returns [`CatalogError::Parse`] when `source` is not valid TOML.
    pub fn toml_layer(
        mut self,
        name: impl Into<String>,
        source: &str,
    ) -> Result<Self, CatalogError> {
        let name = name.into();
        let value = parse_layer(&name, source)?;
        self.layers.push(Layer {
            name,
            source: LayerSource::Toml(value),
        });
        Ok(self)
    }

    /// Adds an unnamed TOML layer.
    ///
    /// The layer is named `overlay 1`, `overlay 2`, and so on by position. Use
    /// [`CatalogBuilder::toml_layer`] to choose a more useful name.
    ///
    /// # Errors
    ///
    /// Returns [`CatalogError::Parse`] when `source` is not valid TOML.
    pub fn overlay_toml(mut self, source: &str) -> Result<Self, CatalogError> {
        self.overlays += 1;
        let name = format!("overlay {}", self.overlays);
        self.toml_layer(name, source)
    }

    /// Merges every layer and validates the result.
    ///
    /// # Errors
    ///
    /// Returns [`CatalogError::Parse`] when a merged provider does not match
    /// the catalog schema, [`CatalogError::Layer`] when a provider fails
    /// validation and its layer is known, and the underlying
    /// [`CatalogError`] otherwise.
    pub fn build(self) -> Result<Catalog, CatalogError> {
        let mut merged = Value::Table(Map::new());
        let mut origins = LayerOrigins::new();
        for layer in self.layers {
            match layer.source {
                LayerSource::Builtin => {
                    for (name, value) in builtin_layers()? {
                        record_origins(&mut origins, name, &value);
                        merge(&mut merged, value);
                    }
                }
                LayerSource::Toml(value) => {
                    record_origins(&mut origins, &layer.name, &value);
                    merge(&mut merged, value);
                }
            }
        }

        let raw: RawDocument = merged.try_into().map_err(|source| CatalogError::Parse {
            layer: MERGED_LAYER.to_owned(),
            source,
        })?;

        let mut providers = BTreeMap::new();
        for (provider_id, value) in raw.providers {
            let layer = origins
                .get(&provider_id)
                .cloned()
                .unwrap_or_else(|| MERGED_LAYER.to_owned());
            let provider: super::provider::ProviderRecord = value
                .try_into()
                .map_err(|source| CatalogError::Parse { layer, source })?;
            providers.insert(provider_id, provider);
        }

        Catalog::from_document(
            ParsedCatalogDocument {
                schema_version: raw.schema_version,
                providers,
            },
            &origins,
        )
    }
}

fn parse_layer(layer: &str, source: &str) -> Result<Value, CatalogError> {
    toml::from_str(source).map_err(|error| CatalogError::Parse {
        layer:  layer.to_owned(),
        source: error,
    })
}

/// Records `layer` as the most recent writer of every provider it declares.
fn record_origins(origins: &mut LayerOrigins, layer: &str, value: &Value) {
    let Some(Value::Table(providers)) = value.get("providers") else {
        return;
    };
    for name in providers.keys() {
        origins.insert(ProviderId::new(name.clone()), layer.to_owned());
    }
}

#[cfg(feature = "builtin-catalog")]
fn builtin_layers() -> Result<Vec<(&'static str, Value)>, CatalogError> {
    BUILTIN_FILES
        .iter()
        .map(|(name, source)| Ok((*name, parse_layer(name, source)?)))
        .collect()
}

#[cfg(not(feature = "builtin-catalog"))]
fn builtin_layers() -> Result<Vec<(&'static str, Value)>, CatalogError> {
    Err(CatalogError::BuiltinCatalogDisabled)
}

#[cfg(test)]
mod tests {
    use std::error::Error as StdError;

    use serde::Deserialize;

    use super::{Catalog, CatalogError};
    #[cfg(feature = "builtin-catalog")]
    use crate::catalog::{AuthScheme, Metadata, ProviderId};
    #[cfg(feature = "builtin-catalog")]
    use crate::types::Speed;

    /// The agent profiles a catalog row may name under `metadata.agent`.
    ///
    /// An agent runtime picks one prompting and tool convention per route from
    /// this value, so an unknown string is a build failure there rather than a
    /// fallback. Every consumer of the namespace shares this vocabulary.
    #[cfg(feature = "builtin-catalog")]
    const AGENT_PROFILES: [&str; 7] = [
        "anthropic",
        "claude-5",
        "openai",
        "gemini",
        "kimi",
        "gpt56",
        "gpt6",
    ];

    const BASE: &str = r#"
        schema_version = 1

        [providers.first]
        display_name = "First"
        adapter = "custom"
        codec = "custom"
        base_url = "https://example.com"
        auth = { type = "none" }

        [providers.first.models.model]
        display_name = "Model"
        api_model = "model"
    "#;

    #[derive(Debug, Deserialize, Eq, PartialEq)]
    struct AppMetadata {
        latency: String,
        nested:  Nested,
    }

    #[derive(Debug, Deserialize, Eq, PartialEq)]
    struct Nested {
        enabled: bool,
        count:   u64,
    }

    /// The shared `agent` metadata namespace, read the way its consumers
    /// read it.
    #[cfg(feature = "builtin-catalog")]
    #[derive(Debug, Deserialize)]
    struct AgentMetadata {
        profile: Option<String>,
    }

    /// The agent profile a row names, if it names one.
    #[cfg(feature = "builtin-catalog")]
    fn agent_profile(metadata: &Metadata) -> Result<Option<String>, Box<dyn StdError>> {
        Ok(metadata
            .namespace::<AgentMetadata>("agent")?
            .and_then(|agent| agent.profile))
    }

    #[test]
    fn external_layers_add_no_built_in_entry() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .build()?;

        assert_eq!(catalog.providers().len(), 1);
        assert!(catalog.provider("openai").is_err());
        assert!(catalog.provider("anthropic").is_err());
        assert!(catalog.models_matching("gpt-5.6-luna").is_empty());
        Ok(())
    }

    #[test]
    fn merges_named_layers_in_call_order() -> Result<(), Box<dyn StdError>> {
        let priority = r"
            [providers.first]
            priority = 10
        ";
        let second = r#"
            [providers.second]
            display_name = "Second"
            adapter = "custom"
            codec = "custom"
            base_url = "https://second.example.com"
            auth = { type = "none" }
        "#;
        let later = r"
            [providers.first]
            priority = 20
        ";

        let catalog = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("providers/first.toml", priority)?
            .toml_layer("providers/second.toml", second)?
            .toml_layer("overrides.toml", later)?
            .build()?;

        let ids = catalog
            .providers()
            .map(|provider| provider.id().as_str().to_owned())
            .collect::<Vec<_>>();

        assert_eq!(ids, vec!["first".to_owned(), "second".to_owned()]);
        assert_eq!(catalog.provider("first")?.priority(), 20);
        Ok(())
    }

    #[test]
    fn reports_the_layer_name_for_invalid_toml() -> Result<(), Box<dyn StdError>> {
        let result = Catalog::builder().toml_layer("providers/broken.toml", "not = = toml");

        let Err(CatalogError::Parse { layer, .. }) = result.map(|_| ()) else {
            return Err("expected a parse failure".into());
        };
        assert_eq!(layer, "providers/broken.toml");
        Ok(())
    }

    #[test]
    fn reports_the_layer_name_for_a_validation_failure() -> Result<(), Box<dyn StdError>> {
        let broken = r#"
            [providers.first]
            default_model = "missing"
        "#;

        let result = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("providers/first.toml", broken)?
            .build();

        let Err(CatalogError::Layer { layer, source }) = result else {
            return Err("expected a layer failure".into());
        };
        assert_eq!(layer, "providers/first.toml");
        assert!(matches!(
            *source,
            CatalogError::UnknownDefaultModel { model, .. } if model == "missing"
        ));
        Ok(())
    }

    #[test]
    fn reports_the_layer_name_for_an_unknown_provider_field() -> Result<(), Box<dyn StdError>> {
        let unknown = r#"
            [providers.first]
            base_urls = "https://example.com"
        "#;

        let result = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("providers/first.toml", unknown)?
            .build();

        let Err(CatalogError::Parse { layer, source }) = result else {
            return Err("expected a schema failure".into());
        };
        assert_eq!(layer, "providers/first.toml");
        assert!(source.to_string().contains("base_urls"));
        Ok(())
    }

    #[test]
    fn rejects_an_unknown_model_field() -> Result<(), Box<dyn StdError>> {
        let unknown = r"
            [providers.first.models.model]
            context_window = 4096
        ";

        let result = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("providers/first.toml", unknown)?
            .build();

        let Err(CatalogError::Parse { layer, source }) = result else {
            return Err("expected a schema failure".into());
        };
        assert_eq!(layer, "providers/first.toml");
        assert!(source.to_string().contains("context_window"));
        Ok(())
    }

    #[test]
    fn round_trips_namespaced_metadata() -> Result<(), Box<dyn StdError>> {
        let first = r#"
            [providers.first.models.model.metadata.app]
            latency = "fast"
            nested = { enabled = true }
        "#;
        let second = r"
            [providers.first.models.model.metadata.app.nested]
            count = 2
        ";

        let catalog = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("app/first.toml", first)?
            .toml_layer("app/second.toml", second)?
            .build()?;

        let metadata = catalog
            .model("first", "model")?
            .metadata()
            .namespace::<AppMetadata>("app")?
            .ok_or("app metadata should be present")?;

        assert_eq!(metadata, AppMetadata {
            latency: "fast".to_owned(),
            nested:  Nested {
                enabled: true,
                count:   2,
            },
        });
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn overlays_catalog_and_recursively_merges_metadata() -> Result<(), Box<dyn StdError>> {
        let first = r#"
            [providers.openai.models."gpt-5.6-luna".metadata.app]
            latency = "fast"
            nested = { enabled = true }
        "#;
        let second = r#"
            [providers.openai.models."gpt-5.6-luna".metadata.app.nested]
            count = 2
        "#;
        let catalog = Catalog::builder()
            .with_builtin()
            .overlay_toml(first)?
            .overlay_toml(second)?
            .build()?;

        let metadata = catalog
            .model("openai", "luna")?
            .metadata()
            .namespace::<AppMetadata>("app")?
            .ok_or("app metadata should be present")?;
        assert_eq!(metadata, AppMetadata {
            latency: "fast".to_owned(),
            nested:  Nested {
                enabled: true,
                count:   2,
            },
        });
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn names_unnamed_overlays_by_position() -> Result<(), Box<dyn StdError>> {
        let broken = r#"
            [providers.openai]
            default_model = "missing"
        "#;

        let result = Catalog::builder()
            .with_builtin()
            .overlay_toml("")?
            .overlay_toml(broken)?
            .build();

        let Err(CatalogError::Layer { layer, .. }) = result else {
            return Err("expected a layer failure".into());
        };
        assert_eq!(layer, "overlay 2");
        Ok(())
    }

    /// The providers that ship disabled, each for a reason an API key cannot
    /// fix: Bedrock needs AWS setup, and LiteLLM, Modal, and Ollama have no
    /// portable model roster. Every other built-in provider needs only a
    /// key, so credentials decide whether it is ready and the catalog leaves
    /// it enabled.
    #[cfg(feature = "builtin-catalog")]
    const DISABLED_BY_DESIGN: [&str; 5] =
        ["bedrock", "bedrock-openai", "litellm", "modal", "ollama"];

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn key_only_builtin_providers_ship_enabled() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;
        let mut disabled: Vec<&str> = catalog
            .providers()
            .filter(|provider| !provider.is_enabled())
            .map(|provider| provider.id().as_str())
            .collect();
        disabled.sort_unstable();
        assert_eq!(disabled, DISABLED_BY_DESIGN);
        Ok(())
    }

    /// The resolver splits a request selector on its first `/`, so a model id
    /// with a slash could never be selected; the provider's wire id is where
    /// a namespaced name belongs.
    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn builtin_model_ids_never_contain_a_slash() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;
        for provider in catalog.providers() {
            for model in provider.models() {
                assert!(
                    !model.id().as_str().contains('/'),
                    "{}/{} has a slash in its catalog id",
                    provider.id(),
                    model.id()
                );
            }
        }
        Ok(())
    }

    /// Every selector a row declares reaches that row through the provider,
    /// and every provider default names a row it carries.
    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn builtin_selectors_resolve_to_the_rows_that_declare_them() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;
        for provider in catalog.providers() {
            let id = provider.id().as_str();
            if let Some(default) = provider.default_model() {
                catalog
                    .model(id, default)
                    .map_err(|error| format!("{id} default `{default}`: {error}"))?;
            }
            for model in provider.models() {
                let mut selectors = vec![model.id().as_str()];
                selectors.extend(model.aliases().iter().map(String::as_str));
                for selector in selectors {
                    let found = catalog
                        .model(id, selector)
                        .map_err(|error| format!("{id}/{selector}: {error}"))?;
                    assert_eq!(found.id(), model.id(), "{id}/{selector}");
                }
            }
        }
        Ok(())
    }

    /// A priced row prices both directions, and a long-context tier starts
    /// inside the model's window, or it could never apply.
    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn builtin_pricing_is_complete_and_tiers_sit_inside_the_window() -> Result<(), Box<dyn StdError>>
    {
        let catalog = Catalog::builder().with_builtin().build()?;
        for provider in catalog.providers() {
            for model in provider.models() {
                let Some(pricing) = model.pricing() else {
                    continue;
                };
                let route = format!("{}/{}", provider.id(), model.id());
                assert!(
                    pricing
                        .input_usd_micros_per_million
                        .is_some_and(|rate| rate > 0),
                    "{route} prices no input"
                );
                assert!(
                    pricing
                        .output_usd_micros_per_million
                        .is_some_and(|rate| rate > 0),
                    "{route} prices no output"
                );
                if let (Some(long_context), Some(limits)) = (pricing.long_context, model.limits()) {
                    assert!(
                        long_context.above_input_tokens < limits.context_tokens,
                        "{route} starts its long-context tier past its window"
                    );
                }
            }
        }
        Ok(())
    }

    /// A protocol option refines how a claimed capability is encoded, so a
    /// row that opts into effort names or cache breakpoints must claim the
    /// capability the option refines.
    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn builtin_protocol_options_refine_claimed_capabilities() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;
        for provider in catalog.providers() {
            for model in provider.models() {
                let route = format!("{}/{}", provider.id(), model.id());
                let options = model.protocol_options();
                let capabilities = model.capabilities();
                if options.reasoning_effort_levels {
                    assert!(
                        !capabilities.reasoning().is_unsupported(),
                        "{route} names effort levels without claiming reasoning"
                    );
                }
                if options.cache_breakpoints {
                    assert!(
                        !capabilities.caching().is_unsupported(),
                        "{route} takes cache breakpoints without claiming caching"
                    );
                }
            }
        }
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn the_builtin_modal_provider_is_portable_passthrough() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        let modal = catalog.provider("modal")?;
        assert!(matches!(modal.auth(), AuthScheme::Headers));
        assert!(modal.allows_passthrough());
        assert!(modal.default_model().is_none());
        assert_eq!(modal.models().len(), 0);
        assert_eq!(agent_profile(modal.metadata())?.as_deref(), Some("kimi"));
        assert!(!modal.is_enabled(), "modal ships as an opt-in provider");
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn the_builtin_codex_provider_mirrors_the_platform_roster() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        let codex = catalog.provider("openai-codex")?;
        assert!(codex.is_enabled());
        assert_eq!(
            codex.stands_in_for().map(ProviderId::as_str),
            Some("openai")
        );
        assert_eq!(codex.default_model(), Some("gpt-5.6-sol"));
        assert!(codex.allows_passthrough());
        assert!(codex.priority() < catalog.provider("openai")?.priority());
        assert_eq!(
            codex.adapter_options()["mode"].as_str(),
            Some("codex"),
            "the codex adapter mode selects the deployment's dialect"
        );

        // The platform roster minus the pro rows, under the same ids and
        // aliases so a stand-in route resolves the same selector.
        let platform = catalog.provider("openai")?;
        let mut expected: Vec<_> = platform
            .models()
            .map(|model| model.id().as_str())
            .filter(|id| !id.ends_with("-pro") && *id != "gpt-6-astra")
            .collect();
        expected.sort_unstable();
        let mut actual: Vec<_> = codex.models().map(|model| model.id().as_str()).collect();
        actual.sort_unstable();
        assert_eq!(actual, expected);
        for model in codex.models() {
            let twin = platform
                .model(model.id().as_str())
                .ok_or_else(|| format!("{} should exist on the platform", model.id()))?;
            assert_eq!(model.aliases(), twin.aliases(), "{}", model.id());
            assert_eq!(model.limits(), twin.limits(), "{}", model.id());
            assert_eq!(model.family(), twin.family(), "{}", model.id());
            // Seat-billed: no per-token price, no sampling, no speed tiers.
            assert!(model.pricing().is_none(), "{}", model.id());
            assert!(
                !model.capabilities().sampling().is_supported(),
                "{}",
                model.id()
            );
            assert!(
                !model.capabilities().speed(Speed::Fast).is_supported(),
                "{}",
                model.id()
            );
        }
        assert_eq!(
            catalog.model("openai-codex", "sol")?.api_model(),
            "gpt-5.6-sol"
        );
        assert!(catalog.model("openai-codex", "gpt-5.4-mini")?.is_probe());
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn a_model_agent_profile_overrides_its_provider() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        // The Anthropic provider row carries the profile a passthrough model
        // and every Claude 4.x row get; the Claude 5 rows name the current
        // harness instead, because that profile is scoped to the models
        // trained against it.
        assert_eq!(
            agent_profile(catalog.provider("anthropic")?.metadata())?.as_deref(),
            Some("anthropic")
        );
        assert_eq!(
            agent_profile(catalog.model("anthropic", "sonnet")?.metadata())?.as_deref(),
            Some("claude-5")
        );
        assert_eq!(
            agent_profile(catalog.model("anthropic", "claude-sonnet-4.6")?.metadata())?,
            None
        );
        // Kimi is profiled per model wherever it is served, so a Kimi row on
        // an Anthropic-profiled or OpenAI-profiled provider still says `kimi`.
        assert_eq!(
            agent_profile(catalog.model("bedrock", "kimi-k2.5")?.metadata())?.as_deref(),
            Some("kimi")
        );
        assert_eq!(
            agent_profile(catalog.model("openrouter", "kimi-k3")?.metadata())?.as_deref(),
            Some("kimi")
        );
        assert_eq!(
            agent_profile(catalog.model("openai", "astra")?.metadata())?.as_deref(),
            Some("gpt6")
        );

        // A model row that names no profile of its own leaves the provider's
        // value in force.
        assert_eq!(
            agent_profile(catalog.model("openai", "gpt-5.4")?.metadata())?,
            None
        );
        assert_eq!(
            agent_profile(catalog.provider("openai")?.metadata())?.as_deref(),
            Some("openai")
        );
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn every_builtin_row_resolves_a_known_agent_profile() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        for provider in catalog.providers() {
            let id = provider.id();
            let default = agent_profile(provider.metadata())?
                .ok_or_else(|| format!("provider `{id}` names no agent profile"))?;
            assert!(
                AGENT_PROFILES.contains(&default.as_str()),
                "provider `{id}` names the unknown agent profile `{default}`"
            );

            for model in provider.models() {
                let profile = agent_profile(model.metadata())?.unwrap_or_else(|| default.clone());
                assert!(
                    AGENT_PROFILES.contains(&profile.as_str()),
                    "`{id}/{}` resolves the unknown agent profile `{profile}`",
                    model.id()
                );
            }
        }
        Ok(())
    }

    #[test]
    fn rejects_provider_alias_that_collides_with_an_id() -> Result<(), Box<dyn StdError>> {
        let source = r#"
            schema_version = 1
            [providers.first]
            display_name = "First"
            aliases = ["second"]
            adapter = "custom"
            codec = "custom"
            base_url = "https://example.com"
            auth = { type = "none" }

            [providers.second]
            display_name = "Second"
            adapter = "custom"
            codec = "custom"
            base_url = "https://example.com"
            auth = { type = "none" }
        "#;

        let result = Catalog::builder().overlay_toml(source)?.build();

        let Err(CatalogError::Layer { source, .. }) = result else {
            return Err("expected a layer failure".into());
        };
        assert!(matches!(
            *source,
            CatalogError::DuplicateProviderAlias { alias } if alias == "second"
        ));
        Ok(())
    }

    #[test]
    fn rejects_duplicate_model_selector_within_provider() -> Result<(), Box<dyn StdError>> {
        let source = r#"
            schema_version = 1
            [providers.test]
            display_name = "Test"
            adapter = "custom"
            codec = "custom"
            base_url = "https://example.com"
            auth = { type = "none" }

            [providers.test.models.first]
            display_name = "First"
            aliases = ["shared"]
            api_model = "first"

            [providers.test.models.second]
            display_name = "Second"
            aliases = ["shared"]
            api_model = "second"
        "#;

        let result = Catalog::builder().overlay_toml(source)?.build();

        let Err(CatalogError::Layer { layer, source }) = result else {
            return Err("expected a layer failure".into());
        };
        assert_eq!(layer, "overlay 1");
        assert!(matches!(
            *source,
            CatalogError::DuplicateModelSelector { provider, selector }
                if provider.as_str() == "test" && selector == "shared"
        ));
        Ok(())
    }
}
