use std::collections::BTreeMap;

use serde::Deserialize;
use toml::Value;
use toml::map::Map;

use super::overlay::merge;
use super::{Catalog, CatalogDocument, CatalogError, CatalogProvider, LayerOrigins, ProviderId};

// `BUILTIN_FILES`: the built-in reference catalog, one file per provider.
// Generated by `build.rs` from `src/catalog/builtin/*.toml`, so growing the
// catalog by one provider means adding one file and nothing else. A parse or
// validation failure names the exact file.
include!(concat!(env!("OUT_DIR"), "/builtin_files.rs"));

/// The layer name reported when a failure belongs to no single layer.
const MERGED_LAYER: &str = "<merged catalog>";

struct Layer {
    name:   String,
    source: LayerSource,
}

enum LayerSource {
    Builtin,
    Toml(Value),
}

/// The merged document before provider entries are given their schema.
///
/// Providers stay as raw TOML so a schema failure can name the layer that
/// last wrote the offending provider.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawDocument {
    schema_version: u32,
    providers:      BTreeMap<ProviderId, Value>,
}

/// Builds an immutable catalog from ordered layers.
///
/// Layers merge in call order and later layers win. Each layer carries a name
/// that appears in parse and validation errors. No layer is added implicitly:
/// a catalog built only from application TOML contains no built-in entry.
#[derive(Default)]
#[must_use]
pub struct CatalogBuilder {
    layers:   Vec<Layer>,
    overlays: usize,
}

impl CatalogBuilder {
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds the built-in reference catalog as the next layers.
    ///
    /// The catalog ships one file per provider; each becomes its own layer,
    /// named `built-in/<provider>.toml`.
    pub fn with_builtin(mut self) -> Self {
        self.layers.push(Layer {
            name:   String::new(),
            source: LayerSource::Builtin,
        });
        self
    }

    /// Adds a named TOML layer.
    ///
    /// `name` identifies the layer in parse and validation errors. A file path
    /// such as `providers/openai.toml` reads well in a message.
    ///
    /// # Errors
    ///
    /// Returns [`CatalogError::Parse`] when `source` is not valid TOML.
    pub fn toml_layer(
        mut self,
        name: impl Into<String>,
        source: &str,
    ) -> Result<Self, CatalogError> {
        let name = name.into();
        let value = parse_layer(&name, source)?;
        self.layers.push(Layer {
            name,
            source: LayerSource::Toml(value),
        });
        Ok(self)
    }

    /// Adds an unnamed TOML layer.
    ///
    /// The layer is named `overlay 1`, `overlay 2`, and so on by position. Use
    /// [`CatalogBuilder::toml_layer`] to choose a more useful name.
    ///
    /// # Errors
    ///
    /// Returns [`CatalogError::Parse`] when `source` is not valid TOML.
    pub fn overlay_toml(mut self, source: &str) -> Result<Self, CatalogError> {
        self.overlays += 1;
        let name = format!("overlay {}", self.overlays);
        self.toml_layer(name, source)
    }

    /// Merges every layer and validates the result.
    ///
    /// # Errors
    ///
    /// Returns [`CatalogError::Parse`] when a merged provider does not match
    /// the catalog schema, [`CatalogError::Layer`] when a provider fails
    /// validation and its layer is known, and the underlying
    /// [`CatalogError`] otherwise.
    pub fn build(self) -> Result<Catalog, CatalogError> {
        let mut merged = Value::Table(Map::new());
        let mut origins = LayerOrigins::new();
        for layer in self.layers {
            match layer.source {
                LayerSource::Builtin => {
                    for (name, value) in builtin_layers()? {
                        record_origins(&mut origins, name, &value);
                        merge(&mut merged, value);
                    }
                }
                LayerSource::Toml(value) => {
                    record_origins(&mut origins, &layer.name, &value);
                    merge(&mut merged, value);
                }
            }
        }

        let raw: RawDocument = merged.try_into().map_err(|source| CatalogError::Parse {
            layer: MERGED_LAYER.to_owned(),
            source,
        })?;

        let mut providers = BTreeMap::new();
        for (provider_id, value) in raw.providers {
            let layer = origins
                .get(&provider_id)
                .cloned()
                .unwrap_or_else(|| MERGED_LAYER.to_owned());
            let provider: CatalogProvider = value
                .try_into()
                .map_err(|source| CatalogError::Parse { layer, source })?;
            providers.insert(provider_id, provider);
        }

        Catalog::from_document(
            CatalogDocument {
                schema_version: raw.schema_version,
                providers,
            },
            &origins,
        )
    }
}

fn parse_layer(layer: &str, source: &str) -> Result<Value, CatalogError> {
    toml::from_str(source).map_err(|error| CatalogError::Parse {
        layer:  layer.to_owned(),
        source: error,
    })
}

/// Records `layer` as the most recent writer of every provider it declares.
fn record_origins(origins: &mut LayerOrigins, layer: &str, value: &Value) {
    let Some(Value::Table(providers)) = value.get("providers") else {
        return;
    };
    for name in providers.keys() {
        origins.insert(ProviderId::new(name.clone()), layer.to_owned());
    }
}

#[cfg(feature = "builtin-catalog")]
fn builtin_layers() -> Result<Vec<(&'static str, Value)>, CatalogError> {
    BUILTIN_FILES
        .iter()
        .map(|(name, source)| Ok((*name, parse_layer(name, source)?)))
        .collect()
}

#[cfg(not(feature = "builtin-catalog"))]
fn builtin_layers() -> Result<Vec<(&'static str, Value)>, CatalogError> {
    Err(CatalogError::BuiltinCatalogDisabled)
}

#[cfg(test)]
mod tests {
    use std::error::Error as StdError;

    use serde::Deserialize;

    use super::{Catalog, CatalogError};
    #[cfg(feature = "builtin-catalog")]
    use crate::types::Speed;

    const BASE: &str = r#"
        schema_version = 1

        [providers.first]
        display_name = "First"
        adapter = "custom"
        codec = "custom"
        base_url = "https://example.com"
        auth = { type = "none" }

        [providers.first.models.model]
        display_name = "Model"
        api_model = "model"
    "#;

    #[derive(Debug, Deserialize, Eq, PartialEq)]
    struct AppMetadata {
        latency: String,
        nested:  Nested,
    }

    #[derive(Debug, Deserialize, Eq, PartialEq)]
    struct Nested {
        enabled: bool,
        count:   u64,
    }

    #[test]
    fn external_layers_add_no_built_in_entry() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .build()?;

        assert_eq!(catalog.providers().len(), 1);
        assert!(catalog.provider("openai").is_err());
        assert!(catalog.provider("anthropic").is_err());
        assert!(catalog.models_matching("gpt-5.6-luna").is_empty());
        Ok(())
    }

    #[test]
    fn merges_named_layers_in_call_order() -> Result<(), Box<dyn StdError>> {
        let priority = r"
            [providers.first]
            priority = 10
        ";
        let second = r#"
            [providers.second]
            display_name = "Second"
            adapter = "custom"
            codec = "custom"
            base_url = "https://second.example.com"
            auth = { type = "none" }
        "#;
        let later = r"
            [providers.first]
            priority = 20
        ";

        let catalog = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("providers/first.toml", priority)?
            .toml_layer("providers/second.toml", second)?
            .toml_layer("overrides.toml", later)?
            .build()?;

        let ids = catalog
            .providers()
            .map(|provider| provider.id().as_str().to_owned())
            .collect::<Vec<_>>();

        assert_eq!(ids, vec!["first".to_owned(), "second".to_owned()]);
        assert_eq!(catalog.provider("first")?.priority(), 20);
        Ok(())
    }

    #[test]
    fn reports_the_layer_name_for_invalid_toml() -> Result<(), Box<dyn StdError>> {
        let result = Catalog::builder().toml_layer("providers/broken.toml", "not = = toml");

        let Err(CatalogError::Parse { layer, .. }) = result.map(|_| ()) else {
            return Err("expected a parse failure".into());
        };
        assert_eq!(layer, "providers/broken.toml");
        Ok(())
    }

    #[test]
    fn reports_the_layer_name_for_a_validation_failure() -> Result<(), Box<dyn StdError>> {
        let broken = r#"
            [providers.first]
            default_model = "missing"
        "#;

        let result = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("providers/first.toml", broken)?
            .build();

        let Err(CatalogError::Layer { layer, source }) = result else {
            return Err("expected a layer failure".into());
        };
        assert_eq!(layer, "providers/first.toml");
        assert!(matches!(
            *source,
            CatalogError::UnknownDefaultModel { model, .. } if model == "missing"
        ));
        Ok(())
    }

    #[test]
    fn reports_the_layer_name_for_an_unknown_provider_field() -> Result<(), Box<dyn StdError>> {
        let unknown = r#"
            [providers.first]
            base_urls = "https://example.com"
        "#;

        let result = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("providers/first.toml", unknown)?
            .build();

        let Err(CatalogError::Parse { layer, source }) = result else {
            return Err("expected a schema failure".into());
        };
        assert_eq!(layer, "providers/first.toml");
        assert!(source.to_string().contains("base_urls"));
        Ok(())
    }

    #[test]
    fn rejects_an_unknown_model_field() -> Result<(), Box<dyn StdError>> {
        let unknown = r"
            [providers.first.models.model]
            context_window = 4096
        ";

        let result = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("providers/first.toml", unknown)?
            .build();

        let Err(CatalogError::Parse { layer, source }) = result else {
            return Err("expected a schema failure".into());
        };
        assert_eq!(layer, "providers/first.toml");
        assert!(source.to_string().contains("context_window"));
        Ok(())
    }

    #[test]
    fn round_trips_namespaced_metadata() -> Result<(), Box<dyn StdError>> {
        let first = r#"
            [providers.first.models.model.metadata.app]
            latency = "fast"
            nested = { enabled = true }
        "#;
        let second = r"
            [providers.first.models.model.metadata.app.nested]
            count = 2
        ";

        let catalog = Catalog::builder()
            .toml_layer("catalog.toml", BASE)?
            .toml_layer("app/first.toml", first)?
            .toml_layer("app/second.toml", second)?
            .build()?;

        let metadata = catalog
            .model("first", "model")?
            .metadata()
            .namespace::<AppMetadata>("app")?
            .ok_or("app metadata should be present")?;

        assert_eq!(metadata, AppMetadata {
            latency: "fast".to_owned(),
            nested:  Nested {
                enabled: true,
                count:   2,
            },
        });
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn overlays_catalog_and_recursively_merges_metadata() -> Result<(), Box<dyn StdError>> {
        let first = r#"
            [providers.openai.models."gpt-5.6-luna".metadata.app]
            latency = "fast"
            nested = { enabled = true }
        "#;
        let second = r#"
            [providers.openai.models."gpt-5.6-luna".metadata.app.nested]
            count = 2
        "#;
        let catalog = Catalog::builder()
            .with_builtin()
            .overlay_toml(first)?
            .overlay_toml(second)?
            .build()?;

        let metadata = catalog
            .model("openai", "luna")?
            .metadata()
            .namespace::<AppMetadata>("app")?
            .ok_or("app metadata should be present")?;
        assert_eq!(metadata, AppMetadata {
            latency: "fast".to_owned(),
            nested:  Nested {
                enabled: true,
                count:   2,
            },
        });
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn names_unnamed_overlays_by_position() -> Result<(), Box<dyn StdError>> {
        let broken = r#"
            [providers.openai]
            default_model = "missing"
        "#;

        let result = Catalog::builder()
            .with_builtin()
            .overlay_toml("")?
            .overlay_toml(broken)?
            .build();

        let Err(CatalogError::Layer { layer, .. }) = result else {
            return Err("expected a layer failure".into());
        };
        assert_eq!(layer, "overlay 2");
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn the_builtin_venice_provider_carries_the_merged_roster() -> Result<(), Box<dyn StdError>> {
        let catalog = Catalog::builder().with_builtin().build()?;

        let venice = catalog.provider("venice")?;
        assert_eq!(venice.models().len(), 16);
        assert_eq!(venice.default_model(), Some("deepseek-v4-flash"));
        assert!(
            venice.default_options().contains_key("venice_parameters"),
            "the venice row should turn off the injected system prompt"
        );

        // The fabro aliases survive and resolve to the verified wire ids.
        assert_eq!(
            catalog.model("venice", "kimi-fast")?.api_model(),
            "kimi-k3-fast-api"
        );
        assert_eq!(
            catalog.model("venice", "deepseek")?.api_model(),
            "deepseek-v4-flash-0731"
        );
        assert_eq!(
            catalog.model("venice", "claude-opus-4.8")?.api_model(),
            "claude-opus-4-8"
        );

        // Live-verified capability corrections win over fabro's claims.
        assert!(
            !catalog
                .model("venice", "qwen3.8-max")?
                .capabilities()
                .structured_output
        );
        assert!(
            catalog
                .model("venice", "kimi-k3")?
                .capabilities()
                .reasoning_effort_levels
        );
        assert!(
            !catalog
                .model("venice", "glm-5.3")?
                .capabilities()
                .reasoning_effort_levels
        );

        // A model id shared with another provider stays reachable through
        // the explicit selector; bare-id resolution is priority-ordered and
        // is pinned by the resolver tests.
        assert_eq!(
            catalog.model("venice", "gpt-5.6-luna")?.api_model(),
            "openai-gpt-56-luna"
        );
        Ok(())
    }

    #[cfg(feature = "builtin-catalog")]
    #[test]
    fn the_builtin_catalog_carries_the_published_rates_and_limits() -> Result<(), Box<dyn StdError>>
    {
        let catalog = Catalog::builder().with_builtin().build()?;

        let luna = catalog.model("openai", "gpt-5.6-luna")?;
        let pricing = luna.pricing().ok_or("gpt-5.6-luna should be priced")?;
        assert_eq!(pricing.input_usd_micros_per_million, Some(1_000_000));
        assert_eq!(pricing.output_usd_micros_per_million, Some(6_000_000));
        assert_eq!(pricing.cached_input_usd_micros_per_million, Some(100_000));
        assert_eq!(
            luna.limits().map(|limits| limits.context_tokens),
            Some(272_000)
        );

        let sonnet = catalog.model("anthropic", "claude-sonnet-4-6")?;
        assert_eq!(
            sonnet.limits().map(|limits| limits.context_tokens),
            Some(200_000)
        );
        assert_eq!(
            sonnet.limits().map(|limits| limits.max_output_tokens),
            Some(64_000)
        );
        let pricing = sonnet
            .pricing()
            .ok_or("claude-sonnet-4-6 should be priced")?;
        // Anthropic bills a cache write at 1.25x input. The entry carries no
        // fast-tier rates, so a fast request keeps the base rates rather than
        // reporting an invented premium.
        assert_eq!(pricing.cache_write_usd_micros_per_million, Some(3_750_000));
        let fast = pricing.for_speed(Some(Speed::Fast));
        assert_eq!(fast.input_usd_micros_per_million, Some(3_000_000));
        assert_eq!(fast.output_usd_micros_per_million, Some(15_000_000));
        assert!(sonnet.capabilities().reasoning_effort_levels);

        // Bedrock on-demand access needs the `us.` inference profile, and the
        // model caches, which the codec gates on.
        let bedrock = catalog.model("bedrock", "anthropic.claude-sonnet-4-6")?;
        assert_eq!(bedrock.api_model(), "us.anthropic.claude-sonnet-4-6");
        assert!(bedrock.capabilities().caching);
        assert!(bedrock.capabilities().reasoning_effort_levels);
        assert_eq!(
            bedrock.limits().map(|limits| limits.max_output_tokens),
            Some(64_000)
        );
        let pricing = bedrock
            .pricing()
            .ok_or("the Bedrock model should be priced")?;
        assert_eq!(pricing.input_usd_micros_per_million, Some(3_000_000));
        assert_eq!(pricing.output_usd_micros_per_million, Some(15_000_000));
        assert_eq!(pricing.cached_input_usd_micros_per_million, Some(300_000));
        assert_eq!(pricing.cache_write_usd_micros_per_million, Some(3_750_000));
        Ok(())
    }

    #[test]
    fn rejects_provider_alias_that_collides_with_an_id() -> Result<(), Box<dyn StdError>> {
        let source = r#"
            schema_version = 1
            [providers.first]
            display_name = "First"
            aliases = ["second"]
            adapter = "custom"
            codec = "custom"
            base_url = "https://example.com"
            auth = { type = "none" }

            [providers.second]
            display_name = "Second"
            adapter = "custom"
            codec = "custom"
            base_url = "https://example.com"
            auth = { type = "none" }
        "#;

        let result = Catalog::builder().overlay_toml(source)?.build();

        let Err(CatalogError::Layer { source, .. }) = result else {
            return Err("expected a layer failure".into());
        };
        assert!(matches!(
            *source,
            CatalogError::DuplicateProviderAlias { alias } if alias == "second"
        ));
        Ok(())
    }

    #[test]
    fn rejects_duplicate_model_selector_within_provider() -> Result<(), Box<dyn StdError>> {
        let source = r#"
            schema_version = 1
            [providers.test]
            display_name = "Test"
            adapter = "custom"
            codec = "custom"
            base_url = "https://example.com"
            auth = { type = "none" }

            [providers.test.models.first]
            display_name = "First"
            aliases = ["shared"]
            api_model = "first"

            [providers.test.models.second]
            display_name = "Second"
            aliases = ["shared"]
            api_model = "second"
        "#;

        let result = Catalog::builder().overlay_toml(source)?.build();

        let Err(CatalogError::Layer { layer, source }) = result else {
            return Err("expected a layer failure".into());
        };
        assert_eq!(layer, "overlay 1");
        assert!(matches!(
            *source,
            CatalogError::DuplicateModelSelector { provider, selector }
                if provider.as_str() == "test" && selector == "shared"
        ));
        Ok(())
    }
}
